### ISSUE TITLE
Can we opt-in instead of opting-out?

### ISSUE THREAD

**Issue by manekinekko** [brminnick/GitHubReadmeWebTrends#16]
Hey, 

Thank you for making sure a great tool. I can definitely see its value when it comes to tracking our content we publish on GitHub. 

I was wondering though if there was an option to allow us to **opt-in** instead of **opting-out**? I'd like to be able to choose which projects should be targeted instead of going over all my repos and opting-out, unless I can opt-out all at once (related https://github.com/brminnick/GitHubReadmeWebTrends/issues/15)?

Cheers.

**Comment by brminnick** [comment]
Thanks Wassim! 

Aaron opened a similar feature request that would solve the same problem: the ability to opt-out/opt-in specific repos: #14 

Let's move the discussion to the existing issue 🙌
