### ISSUE TITLE
PRs include links in JSON files

### ISSUE THREAD

**Issue by waldekmastykarz** [brminnick/GitHubReadmeWebTrends#17]
The tool submits a PR to update URL of a JSON schema, which it shouldn't do. See for example https://github.com/waldekmastykarz/docker-spfx/pull/40/files

**Comment by brminnick** [comment]
Thanks Waldek! 

The tool should definitely be ignoring code blocks and code snippets. I thought I [fixed it before release](https://github.com/brminnick/GitHubReadmeWebTrends/issues/6), but it looks like I missed an edge case 👍

**Comment by waldekmastykarz** [comment]
Happy to help and once again, thanks for making this tool! 👏
