### ISSUE TITLE
Sending PRs to forked repos

### ISSUE THREAD

**Issue by jamesmontemagno** [brminnick/GitHubReadmeWebTrends#8]
It is sending down PRs to the essentials repo. 

Might be good to double check where the PR is going and validate that it is owned by the user.

**Comment by brminnick** [comment]
I totally agree 💯 

I thought I fixed it with [`foreach (var repository in repositoryList?.Where(x => !x.IsFork) ?? Enumerable.Empty<Repository>())`](https://github.com/brminnick/GitHubReadmeWebTrends/blob/55924a5b0cd335dfa4d5299e3c6c1bc1202d8930/GitHubReadmeWebTrends.Functions/Functions/GetGitHubReposFunction.cs#L23).

But running that code just now, I found that this PR snuck through:
https://github.com/xamarinhq/app-geocontacts/pull/53/files

The good news is that I have a reproducible sample now and would be able to nail down this bug!

**Comment by brminnick** [comment]
Turns out the following GitHub GraphQL Query will include all of your repos _and_ all of the repos to which you have write access.

### GraphQL Query

```graphql
query 
{ 
  user(login:"codemillmatt")  
  { 
    login, 
    repositories(first:100) 
    { 
      nodes 
      { 
        id, 
        name, 
        isFork
      }
    }
  }
}
```

### Response

```json
{
  "data": {
    "user": {
      "login": "codemillmatt",
      "repositories": {
        "nodes": [
          {
            "id": "MDEwOlJlcG9zaXRvcnkxMjA1MDAyMzQ=",
            "name": "app-geocontacts",
            "isFork": false
          },
          {
            "id": "MDEwOlJlcG9zaXRvcnkxMzc1MDcwNzI=",
            "name": "app-geocontacts",
            "isFork": true
          },
        ]
      }
    }
  }
}
```

**Comment by brminnick** [comment]
Add `repository.Owner == user.Login`

https://github.com/brminnick/GitHubReadmeWebTrends/blob/7e219e275ff3472440458452a5756c91075db15c/GitHubReadmeWebTrends.Common/Models/RepositoriesConnectionResponse.cs#L14
